=== zchar007/sept/sept-web-2017/src/sept.deploy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/sept.deploy/" targetNamespace="http://www.example.org/sept.deploy/">
    <element name="deploys" type="tns:deploysType"></element>
    
    <complexType name="deploysType">
    	<sequence>
    		<element name="deploy" type="tns:deployType"></element>
    	</sequence>
    </complexType>

    <complexType name="deployType">
    	<sequence>
    		<element name="property" type="tns:propertyType"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    </complexType>
    
    <complexType name="propertyType">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="value" type="string" use="required"></attribute>
    </complexType>
</schema>

=== zchar007/sept/sept-web-2017/src/september-deploy.xml
<?xml version="1.0" encoding="UTF-8"?>
<deploys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="sept.deploy.xsd">
	<deploy type="sql">
		<property name="SPRING-DBNAME" value="applicationContext-jdbc.xml" />
		<property name="SPRING-DBABLE" value="false" />
	</deploy>
	<deploy type="rar">
		<property name="UNRAR" value="./Rar2/UnRAR.exe" />
		<property name="RAR" value="./Rar2/Rar.exe" />
	</deploy>
	<deploy type="debug">
		<property name="DEBUGMODEL" value="true" />
		<property name="DEBUGHEAD" value="" />
	</deploy>
	<deploy type="ftp">
		<property name="FTPURL" value="10.1.82.253" />
		<property name="FTPCLIENTURL" value="ftp://10.1.82.253/" />
		<property name="USER" value="zcharwork@outlook.com" />
		<property name="KEY" value="1118915zcz" />
	</deploy>
	<deploy type="encrypt">
		<property name="txt" value="data" />
		<property name="data" value="txt" />
		<property name="rar" value="bab" />
		<property name="bab" value="rar" />
	</deploy>
	<deploy type="interactivedict">
		<!-- 在web应用中使用，可修改此处 -->
		<!-- 关于前后台交互的一些关键参数key -->
		<!-- 前台——>后台 -->
		<property name="INTERACTIVE_SYSTEM_JSON" value="__SYSTEM_INFO__" />
		<property name="INTERACTIVE_DATA" value="__DATA__" />
		<property name="INTERACTIVE_DATA_TYPE" value="__DATA__TYPE__" />
		<property name="INTERACTIVE_DATA_TYPE_JSON" value="__DATA__TYPE__JSON__" />
		<property name="INTERACTIVE_DATA_TYPE_XML" value="__DATA__TYPE__XML__" />
		<property name="INTERACTIVE_ERROR_FLAG" value="__ERROR__FLAG__" />
		<property name="INTERACTIVE_ERROR_TEXT" value="__ERROR__TEXT__" />
		<property name="INTERACTIVE_ERROR_BUSI" value="__ERROR__BUSI__" />
		<property name="INTERACTIVE_ERROR_APP" value="__ERROR__APP__" />
		<property name="INTERACTIVE_ERROR__FWD__MAIN" value="__ERROR__FWD__MAIN__" />
	</deploy>
</deploys>
